### ISSUE TITLE
Tinker Redirect

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#443] opened 2015-03-24 19:24 UTC
Hi Eric,

In tinker, when trying to redirect links the save buttom doesn't work, or it takes a while for it to show a URL.

**Comment by e-jameson** [comment] 2015-03-24 19:33
The output just isn't being printed on the screen. It is saving the first time, so for now just click save once and refresh the page to put the URL in again to verify. 

Caleb is looking into the cause of the problem

**Comment by e-jameson** [comment] 2015-03-24 19:48
Should be fixed now.

**Closed by e-jameson** 2015-03-24 19:48 UTC
