### ISSUE TITLE
Library News Feed

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#635] opened 2015-11-04 19:45 UTC
Hi Caleb, 
The library news feed on this page https://www.bethel.edu/library/news-events/ is not showing the correct current Nov. events. I checked the library events in events/2015/library and their is 3 upcoming events in Nov. that should be appear but they are not. These events all have the library tagged as well and the event feed block is pulling the correct event feed. Could you see what's going on?

Thanks!

**Comment by c-schwarze** [comment] 2015-11-04 20:03
Well the issue is with the "Events prior to the current date" option in the feed. 

Is this option working how we want it to? @annmarieven could you weigh in maybe?

**Comment by annmarieven** [comment] 2015-11-04 21:41
yep. that's exactly what that field should be doing. so that's the issue... they changed it to 'show' instead of 'hide'. not sure why they would have done that. @ale73233 can you let Will know what's going on? then you can close this issue and the FP job. thanks!

**Closed** 2015-11-05 20:36 UTC
