### ISSUE TITLE
Tag Program Blocks with appropriate metadata

### ISSUE THREAD

**Issue by hamtim** [betheluniversity/cascade#500] opened 2015-05-11 18:00 UTC
1. For program breakdown by cluster, see FP 14616.

2. Add URLs for program pages

**Comment by annmarieven** [comment] 2015-05-12 19:27
@hamtim that FP job is a little confusing... am I suppose to be looking at attachments? If so, which ones?

Can you confirm these are the clusters:

Business and Leadership
Education
Healthcare and Human Services

And clarify where I can find the info about which program goes with which cluster?

Thanks :)

**Comment by annmarieven** [comment] 2015-08-04 18:52
@emily-johnson can you look at job 14616 attachments "Healthcare and Human Services (GS and CAPS) and "Education Postcard June 2015" and "Business and Leadership non-CAPS"

Based on the programs on each attachment, edit the program block and index page for that program to tag the cluster (found in the metadata tab).

let me know if you have any questions!

**Comment by emily-johnson** [comment] 2015-08-05 18:44
@hamtim I tagged the clusters for the programs based on the info from the "CAPS-GS Info Session Postcards Summer 2015-Proof 4.pdf" attached to case 14616.

**Comment by annmarieven** [comment] 2015-09-21 14:42
@emily-johnson did you tag the program blocks or the program pages? @ale73233 created program feeds using the cluster metadata but we're not getting anything to show up in the feeds. I just thought I'd double check! The FP job allie is working on is 15799, just in case you need to reference it.

**Comment by emily-johnson** [comment] 2015-09-21 20:14
I'm not sure what happened but I looked in the program-blocks (CAPS and GS) and some were tagged and some weren't, so if that was the issue, all are tagged now.

**Comment by ale73233** [comment] 2015-09-30 14:14
All of the programs are tagged but they are still not showing up in the feed. 
https://cms.bethel.edu/entity/open.act?id=f05122ea8c58651346a52c6d69553d6b&type=block&
https://cms.bethel.edu/entity/open.act?id=f04474f98c58651346a52c6d6ab3d40d&type=page&

**Comment by ale73233** [comment] 2015-10-07 14:10
Hey Caleb, have you looked into this?

Thanks!

**Comment by c-schwarze** [comment] 2015-10-07 14:38
It looks like you should update the "Degree" field in the metadata instead of the "School" field. Let us know if that should change. 

Pass this to @josiahtillman if you have any questions :)

**Comment by ale73233** [comment] 2015-10-07 15:27
I updated the degree field and checked to make sure all of the tagging was correct and it was, but the correct feeds aren't showing up still.

**Comment by c-schwarze** [comment] 2015-10-07 16:10
Publishing the page fixed it.

**Comment by ale73233** [comment] 2015-10-07 18:15
I still don't think that the programs that are showing are the correct ones since every program is showing the same list?

**Comment by c-schwarze** [comment] 2015-10-07 19:03
It looks like the 3 feeds on the page have every "Degree" value selected.

**Comment by ale73233** [comment] 2015-10-14 14:40
We purposely selected every degree field but the problem is with the cluster in the metadata. For example the business leadership program feed's cluster in the metadata is tagged as Business and Leadership but it still isn't showing the specific feeds for business and leadership on the main index page.

**Comment by c-schwarze** [comment] 2015-10-14 14:51
@c-varberg Could you look at this?

**Comment by c-varberg** [comment] 2015-10-15 18:20
The code right now is set up assuming that you will only select one degree which is part of the problem, it also is not checking the cluster at all. I'll work on refactoring it

**Comment by c-varberg** [comment] 2015-10-15 18:41
@ale73233 This should be working now. Let me know if anything looks off.

**Comment by annmarieven** [comment] 2015-10-16 20:31
@ale73233 can you confirm this is working and close the issue if it is?

**Comment by e-jameson** [comment] 2015-12-07 20:57
@ale73233 @annmarieven any progress on this?

**Comment by ale73233** [comment] 2015-12-10 21:41
everything is working!

**Closed by ale73233** 2015-12-10 21:41 UTC
Labels: enhancement
